name: flutter_secure_storage_platform_interface
publish_to: none
description: A common platform interface for the flutter_secure_storage plugin.
homepage: https://github.com/mogol/flutter_secure_storage
version: 2.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  very_good_analysis: ^7.0.0
